name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.14
      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Assembly
        run: sbt "project secret-provider" assembly
        env:
          LENSES_TAG_NAME: ${{ steps.get_tag.outputs.VERSION }}
      - name: Copy file
        run: cp secret-provider/target/libs/secret-provider-assembly-${{ steps.get_tag.outputs.VERSION }}.jar secret-provider/target/libs/secret-provider-${{ steps.get_tag.outputs.VERSION }}-all.jar
      - name: Release to Github
        uses: softprops/action-gh-release@v1
        with:
          files: |
            secret-provider/target/libs/secret-provider-${{ steps.get_tag.outputs.VERSION }}-all.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LENSES_TAG_NAME: ${{ steps.get_tag.outputs.VERSION }}
